<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Корзина");
?>
<script>window.basketJSParams = window.basketJSParams || [];</script>
<?$APPLICATION->IncludeComponent(
	"bitrix:sale.basket.basket", 
	"v2", 
	array(
		"COLUMNS_LIST" => array(
			0 => "NAME",
			1 => "DISCOUNT",
			2 => "PROPS",
			3 => "DELETE",
			4 => "DELAY",
			5 => "TYPE",
			6 => "PRICE",
			7 => "QUANTITY",
			8 => "SUM",
		),
		"OFFERS_PROPS" => array(
			0 => "COLOR_REF",
			1 => "SIZES",
		),
		"PATH_TO_ORDER" => SITE_DIR."order/",
		"HIDE_COUPON" => "Y",
		"PRICE_VAT_SHOW_VALUE" => "Y",
		"COUNT_DISCOUNT_4_ALL_QUANTITY" => "N",
		"USE_PREPAYMENT" => "N",
		"SET_TITLE" => "N",
		"AJAX_MODE_CUSTOM" => "Y",
		"SHOW_MEASURE" => "Y",
		"PICTURE_WIDTH" => "100",
		"PICTURE_HEIGHT" => "100",
		"SHOW_FULL_ORDER_BUTTON" => "Y",
		"SHOW_FAST_ORDER_BUTTON" => "Y",
		"COMPONENT_TEMPLATE" => "v2",
		"QUANTITY_FLOAT" => "N",
		"ACTION_VARIABLE" => "action",
		"TEMPLATE_THEME" => "blue",
		"AUTO_CALCULATION" => "Y",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"USE_GIFTS" => "Y",
		"GIFTS_PLACE" => "BOTTOM",
		"GIFTS_BLOCK_TITLE" => "Выберите один из подарков",
		"GIFTS_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_TEXT_LABEL_GIFT" => "Подарок",
		"GIFTS_PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"GIFTS_PRODUCT_PROPS_VARIABLE" => "prop",
		"GIFTS_SHOW_OLD_PRICE" => "Y",
		"GIFTS_SHOW_DISCOUNT_PERCENT" => "Y",
		"GIFTS_SHOW_NAME" => "Y",
		"GIFTS_SHOW_IMAGE" => "Y",
		"GIFTS_MESS_BTN_BUY" => "Выбрать",
		"GIFTS_MESS_BTN_DETAIL" => "Подробнее",
		"GIFTS_PAGE_ELEMENT_COUNT" => "4",
		"GIFTS_CONVERT_CURRENCY" => "N",
		"GIFTS_HIDE_NOT_AVAILABLE" => "N",
		"EMPTY_BASKET_HINT_PATH" => SITE_DIR."catalog/",
		"DEFERRED_REFRESH" => "N",
		"USE_DYNAMIC_SCROLL" => "Y",
		"SHOW_FILTER" => "Y",
		"SHOW_RESTORE" => "Y",
		"COLUMNS_LIST_EXT" => array(
			0 => "PREVIEW_PICTURE",
			1 => "DELETE",
			2 => "DELAY",
			3 => "TYPE",
			4 => "SUM",
			5 => "PROPERTY_IMYIE_STORES4FILTER",
			6 => "PROPERTY_ARTICLE",
		),
		"COLUMNS_LIST_MOBILE" => array(
			0 => "PREVIEW_PICTURE",
			1 => "DELETE",
			2 => "DELAY",
			3 => "TYPE",
			4 => "SUM",
		),
		"TOTAL_BLOCK_DISPLAY" => array(
			0 => "bottom",
		),
		"DISPLAY_MODE" => "extended",
		"PRICE_DISPLAY_MODE" => "Y",
		"SHOW_DISCOUNT_PERCENT" => "Y",
		"DISCOUNT_PERCENT_POSITION" => "bottom-right",
		"PRODUCT_BLOCKS_ORDER" => "props,sku,columns",
		"USE_PRICE_ANIMATION" => "Y",
		"LABEL_PROP" => array(
			0 => "HIT",
		),
		"CORRECT_RATIO" => "Y",
		"COMPATIBLE_MODE" => "Y",
		"ADDITIONAL_PICT_PROP_2" => "-",
		"ADDITIONAL_PICT_PROP_3" => "-",
		"ADDITIONAL_PICT_PROP_29" => "-",
		"ADDITIONAL_PICT_PROP_31" => "-",
		"ADDITIONAL_PICT_PROP_38" => "-",
		"BASKET_IMAGES_SCALING" => "adaptive",
		"USE_ENHANCED_ECOMMERCE" => "Y",
		"LABEL_PROP_MOBILE" => array(
		),
		"LABEL_PROP_POSITION" => "top-center",
		"DATA_LAYER_NAME" => "dataLayer",
		"BRAND_PROPERTY" => "PROPERTY_BRAND_REF"
	),
	false
);?>

<?$APPLICATION->IncludeComponent(
	"bitrix:main.include", 
	"basket", 
	array(
		"COMPONENT_TEMPLATE" => "basket",
		"PATH" => SITE_DIR."include/comp_basket_bigdata.php",
		"AREA_FILE_SHOW" => "file",
		"AREA_FILE_SUFFIX" => "",
		"AREA_FILE_RECURSIVE" => "Y",
		"EDIT_TEMPLATE" => "standard.php",
		"PRICE_CODE" => array(
			0 => "РОЗНИЦА",
			1 => "Субдилер IN HOUM (-30%)",
			2 => "Партнер EKF (-44%)",
			3 => "Субдилер IN HOUM (-23%)",
			4 => "Уценка",
			5 => "ЭНЕРГОМЕРА (Дилер 1 уровень)",
			6 => "Партнер EKF (-47% )",
			7 => "Субдилер IN HOUM (-25%)",
			8 => "Удаленная Партнер МИЛУР",
			9 => "Партнер EKF (-36%)",
			10 => "Партнер ITK -16%",
			11 => "Партнер EKF (-41%)",
			12 => "Партнер ITK -21%",
			13 => "Партнер TDM ( -25%)",
			14 => "Партнер IEK -43%",
			15 => "2. от  5 т.р. (5%)",
			16 => "Партнер TDM ( -16%)",
			17 => "1. от  3  т.р. (3%)",
			18 => "3. от 15 т.р. (8%)",
			19 => "4. от 20  т.р. (10%)",
			20 => "5. от 100 т.р.(крупный ОПТ)",
			21 => "6. для тендеров",
			22 => "ЭНЕРГОМЕРА (Дилер 2 уровень)",
			23 => "Партнер IEK -40%",
			24 => "Партнер IEK -47%",
			25 => "Gauss Распродажа из наличия",
			26 => "Партнер TDM ( -20%)",
			27 => "ЭНЕРГОМЕРА (Дилер 3 уровень)",
			28 => "Партнер ONI -41%",
		),
		"STORES" => array(
			0 => "",
			1 => "1",
			2 => "2",
			3 => "",
		),
		"BIG_DATA_RCM_TYPE" => "personal",
		"STIKERS_PROP" => "HIT",
		"SALE_STIKER" => "SALE_TEXT",
		"SHOW_DISCOUNT_PERCENT_NUMBER" => "Y",
		"PRICE_VAT_INCLUDE" => "Y"
	),
	false
);?>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>