<?if(!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED !== true)
{
	define("STATISTIC_SKIP_ACTIVITY_CHECK", "true");
	require($_SERVER["DOCUMENT_ROOT"]."/bitrix/modules/main/include/prolog_before.php");
}?>
<?$APPLICATION->IncludeComponent(
	"aspro:wrapper.block.max", 
	".default", 
	array(
		"IBLOCK_TYPE" => "catalog_1c",
		"IBLOCK_ID" => "38",
		"FILTER_NAME" => "arRegionLink",
		"COMPONENT_TEMPLATE" => ".default",
		"SECTION_ID" => "",
		"SECTION_CODE" => "",
		"FILTER_PROP_CODE" => "FAVORIT_ITEM",
		"ELEMENT_SORT_FIELD" => "name",
		"ELEMENT_SORT_ORDER" => "desc",
		"ELEMENT_SORT_FIELD2" => "timestamp_x",
		"ELEMENT_SORT_ORDER2" => "desc",
		"INCLUDE_SUBSECTIONS" => "Y",
		"SHOW_ALL_WO_SECTION" => "Y",
		"HIDE_NOT_AVAILABLE" => "Y",
		"ELEMENT_COUNT" => "30",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"DISPLAY_COMPARE" => "Y",
		"SHOW_MEASURE" => "Y",
		"DISPLAY_WISH_BUTTONS" => "Y",
		"SHOW_DISCOUNT_PERCENT" => "Y",
		"SHOW_DISCOUNT_PERCENT_NUMBER" => "Y",
		"SHOW_DISCOUNT_TIME" => "Y",
		"SHOW_OLD_PRICE" => "Y",
		"PROPERTY_CODE" => array(
			0 => "CML2_ARTICLE",
		),
		"PRICE_CODE" => array(
			0 => "Субдилер IN HOUM (-23%)",
			1 => "РОЗНИЦА",
			2 => "Субдилер IN HOUM (-30%)",
			3 => "Уценка",
			4 => "Партнер EKF (-44%)",
			5 => "Партнер EKF (-47% )",
			6 => "Субдилер IN HOUM (-25%)",
			7 => "ЭНЕРГОМЕРА (Дилер 1 уровень)",
			8 => "Удаленная Партнер МИЛУР",
			9 => "Партнер EKF (-36%)",
			10 => "Партнер ITK -16%",
			11 => "Партнер EKF (-41%)",
			12 => "Партнер ITK -21%",
			13 => "Партнер TDM ( -25%)",
			14 => "Партнер IEK -43%",
			15 => "2. от  5 т.р. (5%)",
			16 => "Партнер TDM ( -16%)",
			17 => "1. от  3  т.р. (3%)",
			18 => "3. от 15 т.р. (8%)",
			19 => "4. от 20  т.р. (10%)",
			20 => "5. от 100 т.р.(крупный ОПТ)",
			21 => "6. для тендеров",
			22 => "ЭНЕРГОМЕРА (Дилер 2 уровень)",
			23 => "Партнер IEK -40%",
			24 => "Партнер IEK -47%",
			25 => "Gauss Распродажа из наличия",
			26 => "Партнер TDM ( -20%)",
			27 => "ЭНЕРГОМЕРА (Дилер 3 уровень)",
			28 => "Партнер ONI -41%",
		),
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"PRODUCT_PROPERTIES" => array(
		),
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"SHOW_RATING" => "N",
		"STIKERS_PROP" => "HIT",
		"SALE_STIKER" => "SALE_TEXT",
		"CONVERT_CURRENCY" => "N",
		"TITLE_BLOCK" => "Товар дня",
		"STORES" => array(
			0 => "",
			1 => "",
		),
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"SHOW_GALLERY" => "Y",
		"MAX_GALLERY_ITEMS" => "5",
		"ADD_PICT_PROP" => "MORE_PHOTO",
		"SHOW_ONE_CLICK" => "N",
		"TITLE_BLOCK_ALL" => "Весь каталог",
		"ALL_URL" => "catalog/",
		"USER_FIELDS" => array(
			0 => "",
			1 => "",
		),
		"FIELDS" => array(
			0 => "",
			1 => "",
		)
	),
	false
);?>